version: '3.0'

services:
   db:
     image: public.ecr.aws/lts/mysql:latest
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: accountowner
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: dbuserpassword
     volumes:
       - dbdata:/var/lib/mysql
       - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
     restart: always

   accountownerapp:
     depends_on:
       - db
     image: eppsnet/accountowner:runtime
     build:
       context: .
     ports:
       - "8080:5000"

volumes:
    dbdata: